// Country name to ISO 3166-1 alpha-2 code mapping
export const countryCodeMap: Record<string, string> = {
  'United States': 'US',
  'China': 'CN',
  'India': 'IN',
  'Philippines': 'PH',
  'Pakistan': 'PK',
  'United Kingdom': 'GB',
  'Italy': 'IT',
  'Singapore': 'SG',
  'Germany': 'DE',
  'France': 'FR',
  'Canada': 'CA',
  'Australia': 'AU',
  'Brazil': 'BR',
  'Japan': 'JP',
  'South Korea': 'KR',
  'Spain': 'ES',
  'Netherlands': 'NL',
  'Poland': 'PL',
  'Turkey': 'TR',
  'Mexico': 'MX',
  'Indonesia': 'ID',
  'Thailand': 'TH',
  'Vietnam': 'VN',
  'Malaysia': 'MY',
  'Bangladesh': 'BD',
  'Egypt': 'EG',
  'Saudi Arabia': 'SA',
  'United Arab Emirates': 'AE',
  'South Africa': 'ZA',
  'Argentina': 'AR',
  'Chile': 'CL',
  'Colombia': 'CO',
  'Peru': 'PE',
  'Venezuela': 'VE',
  'Russia': 'RU',
  'Ukraine': 'UA',
  'Greece': 'GR',
  'Portugal': 'PT',
  'Belgium': 'BE',
  'Switzerland': 'CH',
  'Austria': 'AT',
  'Sweden': 'SE',
  'Norway': 'NO',
  'Denmark': 'DK',
  'Finland': 'FI',
  'Ireland': 'IE',
  'New Zealand': 'NZ',
  'Israel': 'IL',
  'Nigeria': 'NG',
  'Kenya': 'KE',
  'Ghana': 'GH',
  'Morocco': 'MA',
  'Algeria': 'DZ',
  'Tunisia': 'TN',
  'Romania': 'RO',
  'Czech Republic': 'CZ',
  'Hungary': 'HU',
  'Bulgaria': 'BG',
  'Croatia': 'HR',
  'Serbia': 'RS',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Lithuania': 'LT',
  'Latvia': 'LV',
  'Estonia': 'EE',
};

export function getCountryCode(countryName: string): string {
  return countryCodeMap[countryName] || '';
}
